#!/usr/bin/env python3
"""Page renderers for the Graphify Obsidian vault (split from build_graph_vault.py to
respect the 150-line file limit). Each writer takes the analysed graph and emits Markdown
with Obsidian wikilinks; no figure is hand-written."""

import pathlib

from build_graph_vault_lib import TOP_NODES, layer_of, slug


def write_index(out: pathlib.Path, graph: dict, a: dict, repo: str, commit: str) -> None:
    lines = [
        f"# {repo} — knowledge-graph index",
        "",
        f"- **Repository:** `{repo}`  ·  **Commit:** `{commit}`",
        f"- **Nodes:** {len(graph['nodes'])}  ·  **Links:** {len(graph['links'])}",
        f"- **Communities:** {len({n.get('community') for n in graph['nodes']})}",
        "",
        "Generated by [Graphify](https://pypi.org/project/graphifyy/) (AST extraction, no LLM)",
        "and rendered for Obsidian. See [[architecture]] and [[hot]].",
        "",
        "## Top hubs by degree",
        "",
        "| # | Node | Degree | Layer | Source |",
        "| ---: | --- | ---: | --- | --- |",
    ]
    for rank, (nid, deg) in enumerate(a["degree"].most_common(TOP_NODES), 1):
        node = a["by_id"].get(nid, {})
        lines.append(
            f"| {rank} | [[nodes/{slug(nid)}\\|{node.get('label', nid)}]] | {deg} | "
            f"`{layer_of(node)}` | `{node.get('source_file', '?')}` |"
        )
    (out / "index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_hot(out: pathlib.Path, a: dict, repo: str) -> None:
    lines = [
        f"# hot — high-connectivity nodes ({repo})",
        "",
        "> Ranked by graph centrality. These are *investigation candidates* for reverse",
        "> engineering — a high degree means many things depend on the node, not that it is",
        "> defective. Nothing here was auto-patched.",
        "",
        "| Rank | Node | Degree | Layer | Why it ranks |",
        "| ---: | --- | ---: | --- | --- |",
    ]
    for rank, (nid, deg) in enumerate(a["degree"].most_common(15), 1):
        node = a["by_id"].get(nid, {})
        reason = "core shared type" if deg > 100 else "widely referenced"
        lines.append(
            f"| {rank} | [[nodes/{slug(nid)}\\|{node.get('label', nid)}]] | {deg} | "
            f"`{layer_of(node)}` | {reason} |"
        )
    (out / "hot.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_architecture(out: pathlib.Path, a: dict, repo: str) -> None:
    lines = [
        f"# Architecture from the graph ({repo})",
        "",
        "## Nodes per layer",
        "",
        "| Layer | Nodes |",
        "| --- | ---: |",
    ]
    for layer, count in a["layers"].most_common():
        lines.append(f"| `{layer}` | {count} |")
    lines += [
        "",
        "## Cross-layer dependencies (edges)",
        "",
        "| From | To | Edges |",
        "| --- | --- | ---: |",
    ]
    for (src, dst), count in a["cross"].most_common(25):
        lines.append(f"| `{src}` | `{dst}` | {count} |")
    (out / "architecture.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_nodes(out: pathlib.Path, a: dict) -> None:
    nodes_dir = out / "nodes"
    nodes_dir.mkdir(parents=True, exist_ok=True)
    top = [nid for nid, _ in a["degree"].most_common(TOP_NODES)]
    for nid in top:
        node = a["by_id"].get(nid, {})
        lines = [
            f"# {node.get('label', nid)}",
            "",
            f"- **Source:** `{node.get('source_file', '?')}` {node.get('source_location', '')}",
            f"- **Layer:** `{layer_of(node)}`  ·  **Degree:** {a['degree'][nid]}",
            f"- **Community:** {node.get('community_name', node.get('community', '?'))}",
            "",
            "## Neighbours",
            "",
        ]
        for other, relation in sorted(a["neighbours"][nid])[:30]:
            label = a["by_id"].get(other, {}).get("label", other)
            link = f"[[nodes/{slug(other)}\\|{label}]]" if other in top else label
            lines.append(f"- `{relation}` {link}")
        lines += ["", "[[index]] · [[hot]] · [[architecture]]"]
        (nodes_dir / f"{slug(nid)}.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
